version: 2.1
orbs:
  codecov: codecov/codecov@1.1.1
jobs:  
  build:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run: npm install
      - run:
          name: "Run Jest and Collect Coverage Reports"
          command: npm run test:coverage
      - codecov/upload