version: 2.1
jobs:  
  build:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run: npm install
      - run:
          name: "Run Jest and Collect Coverage Reports"
          command: npm run test:coverage
      - run:
          name: "Install codecov globally"
          command: sudo npm install -g codecov
      - run:
          name: "Upload coverage"
          command: codecov